name: 'App Center Distribute'
description: 'GitHub Action that uploads artifacts for Visual Studio App Center'
author: 'Seungyong Yun <@devussy>'
inputs: 
  app:
    description: 'App name followed by username e.g. devussy/Sample-App'
    required: true 
  token:
    description: 'Upload token - you can get one from appcenter.ms/settings'
    required: true 
  group:
    description: 'Distribution group'
    required: true
  file:
    description: 'Artifact to upload (.apk or .ipa)'
    required: true
  releaseNotes:
    description: 'Release notes visible on release page'
    required: false
  silent:
    description: 'Flag to determine whether notify testers of this release or not (true/false)'
    required: false
    default: true
branding:
  color: 'red' 
  icon: 'share'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.app }}
    - ${{ inputs.token }}
    - ${{ inputs.group }}
    - ${{ inputs.file }}
    - ${{ inputs.releaseNotes }}
    - ${{ inputs.silent }}
