name: Example workflow for App Center Distribute action
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@master
      - name: Upload artifact to AppCenter  
        uses: ./
        with:
          appName: Test Name 
          token: Test Token
          group: Test Group 
          file: Test File
          silent: true
